docs/AboutUs.md
docs/DeveloperGuide.md
docs/_markbind/layouts/default.md
docs/team/irwyn.md

add my about us and portfolio inside.
I also edited abit of the pages and DG
please review 👌

Add about us and portfolio, edit abit of the DG

---

docs/UserGuide.md

Edited a bit of the features above addPolicy to suit the command format

Edit features of user guide to include addPolicy command

---

docs/DeveloperGuide.md

V1.1 Iteration Manual Testing Appendix Edits

---

docs/DeveloperGuide.md

Add our user stories and edit the appendix for our DG please take a look!
😁

Edit current DG to fit our requirement

---

docs/AboutUs.md
docs/team/jim.md
docs/team/rahul.md
docs/team/udon.md

edit stuff for our about us page.

Add about us for everyone

---

src/main/java/seedu/address/logic/commands/ClientAddCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/model/person/Client.java
src/main/java/seedu/address/model/person/Meeting.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/UniqueClientList.java
src/main/java/seedu/address/model/person/exceptions/ClientNotFoundException.java
src/main/java/seedu/address/model/person/exceptions/DuplicateClientException.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java

Add Guest object and commands to add it, right now got a few test errors but the implementation have no error.
will push once fixed.

Add Client function

---

src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml

Ui for meeting

---

docs/UserGuide.md
src/main/java/seedu/address/model/person/Meeting.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/ui/HelpWindow.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/MeetingsWindow.java
src/main/resources/view/MeetingsWindow.fxml
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java

Meetings command now has working implementation.
No tests written yet for Meetings command but will do that soon.
Closes #44

Implement Meetings command

---

docs/diagrams/DisplayMeetingsSequenceDiagram.puml

Created sequence diagram for displayMeetings() method in MeetingsWindow.

Add displayMeetings() .puml sequence diagram

---

docs/diagrams/UiClassDiagram.puml

Included MeetingsWindow in the .puml file.

Edit UiClassDiagram.puml

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Policy.java
src/main/java/seedu/address/storage/JsonAdaptedPolicyTag.java
src/main/java/seedu/address/ui/MeetingsWindow.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Fixing testcases

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/EditCommand.java

edit meeting field usign the edit function.

Edit command for meeting field

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Policy.java
src/main/java/seedu/address/storage/JsonAdaptedPolicyTag.java

Fix compile error

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Meeting.java
src/main/java/seedu/address/storage/JsonAdaptedMeeting.java

Exceptions for split ui fixed

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java

Ensures split screen updates when command is edited

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/FindPolicyCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/FindPolicyCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/model/person/Meeting.java
src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/PolicyNameContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/UniqueMeetingList.java
src/main/java/seedu/address/model/person/exceptions/DuplicateMeetingException.java
src/main/java/seedu/address/model/person/exceptions/MeetingNotFoundException.java
src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
src/main/java/seedu/address/ui/MeetingCard.java
src/main/java/seedu/address/ui/MeetingListPanel.java

Add findPolicyCommand and change implementation of both find commands to take in both partial and full words

---

src/main/java/seedu/address/logic/commands/FindPolicyCommand.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Meeting.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/ui/MeetingCard.java
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json

Meeting time is now compulsory

Meeting class: User must now input time as well, not just date

---

build.gradle
docs/DeveloperGuide.md
docs/diagrams/ClientClassDiagram.puml

Edit DG for adding of client

---

docs/DeveloperGuide.md
docs/diagrams/DisplayMeetingsSequenceDiagram.puml
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/ui/MeetingCard.java
src/main/resources/view/MeetingListCard.fxml
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java

Swapped the name and meeting in MeetingCard view.
Fixed EditCommand bug.

Edit MeetingCard view

---

src/main/java/seedu/address/logic/commands/AddPolicyCommand.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/PolicyCard.java
src/main/java/seedu/address/ui/PolicyListPanel.java
src/main/resources/view/PolicyCard.fxml
src/main/resources/view/Styles.css

addPolicy: Changed 'poltype/' prefix to just 'type/' to maintain speed for our CLI app.
ViewCommand: Added functionality and extra details to PolicyCard.
closes #77

Complete implementation of 'view' command

---

src/main/java/seedu/address/logic/commands/EditCommand.java

Fixed bug with edit command
Closes #109

EditCommand: fix bug for duplicate meeting

---

src/main/java/seedu/address/ui/MainWindow.java

Fixed NullPointerException for all other non-view commands.

Fix MainWindow Null Exception

---

src/main/java/seedu/address/model/person/Meeting.java
src/main/java/seedu/address/model/util/SampleDataUtil.java

Fixed the issue of loading meetings into the UI for first-time users.
Closes #112

Fix issue with loading of Meetings

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Meeting.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/AddCommandTest.java

Testcase for addcommand

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/DeletePolicyCommand.java
src/test/java/seedu/address/model/person/UniqueMeetingListTest.java

Delete Policy explanation added to UG and Table of Contents created.

Userguide changes to delPolicy and toc adding

---

docs/UserGuide.md

Update 'add' command details
Add a note for 'meetings' command
Closes #174

Improve UG readability

---

docs/UserGuide.md
src/main/java/seedu/address/model/person/Meeting.java
src/main/java/seedu/address/model/person/Policy.java

As per title.
Updated UG as well for Policy: polname max 40 characters allowed
Closes #144 
Closes #153

Fix issues 144 and 153

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddCommand.java

edit ug for issues #147 and #156

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/model/person/Name.java
src/test/java/seedu/address/model/person/NameTest.java

Fixes for v1.4 (Issues 196, 165)

---

docs/diagrams/AddPolicySequenceDiagram.puml
docs/diagrams/BetterModelClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml
docs/diagrams/StorageClassDiagram.puml
docs/diagrams/UiClassDiagram.puml

Update PUML diagram

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/address/model/person/Name.java

DG contains some planned enhancements
Update UG's known issues
closes #140
closes #142 
closes #143 
closes #146 
closes #154 
closes #162 
closes #164

Revert some changes and update UG and DG
